In [11]:
import pandas as pd
import urllib.request
import json

movieListURL="http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieList.json?key=105d650c6cc06c74308970b42deeca5a&itemPerPage=100"
moviePage=urllib.request.urlopen(movieListURL)
movieData=json.loads(moviePage.read().decode("utf8"),encoding="utf8")


movieDOF = pd.DataFrame()
movieDOF_temp = pd.DataFrame()
movieDOF_temp = movieDOF_temp.append({"movieCd":"","movieNm":"","movieNmEn":"","openDt":"","directorpeopleNm":""},ignore_index=True)


temp_movcd_idx=movieDOF_temp.columns.get_loc("movieCd")
temp_movNm_idx=movieDOF_temp.columns.get_loc("movieNm")
temp_movNmEn_idx=movieDOF_temp.columns.get_loc("movieNmEn")
temp_movdt_idx=movieDOF_temp.columns.get_loc("openDt")
temp_movdir_idx=movieDOF_temp.columns.get_loc("directorpeopleNm")

num=len(movieData["movieListResult"]["movieList"])


for i in range(0,num):
    movieDOF_temp.iat[0,temp_movcd_idx]=movieData["movieListResult"]["movieList"][i]["movieCd"]    
    movieDOF_temp.iat[0,temp_movNm_idx]=movieData["movieListResult"]["movieList"][i]["movieNm"]
    movieDOF_temp.iat[0,temp_movNmEn_idx]=movieData["movieListResult"]["movieList"][i]["movieCd"]
    movieDOF_temp.iat[0,temp_movdt_idx]=movieData["movieListResult"]["movieList"][i]["openDt"]
    if movieData["movieListResult"]["movieList"][i]["directors"] !=[]:
        movieDOF_temp.iat[0,temp_movdir_idx]=movieData["movieListResult"]["movieList"][i]["directors"][0]["peopleNm"]
    else:
        pass
    
    movieDOF=movieDOF.append(movieDOF_temp, ignore_index=True)
    
    for j in range(0,len(movieDOF_temp.columns)):
        movieDOF_temp.iat[0,j]=""
        

        
# 컬럼 추가하기
movieDOF["year"] = movieDOF["openDt"].apply(lambda x: str(x)[:4])
movieDOF["month"] = movieDOF["openDt"].apply(lambda x: str(x)[4:6])
movieDOF["day"] = movieDOF["openDt"].apply(lambda x: str(x)[6:])

# 정렬하기
movieDOF=movieDOF.sort_values(by="openDt")
movieDOF=movieDOF.set_index(movieDOF.columns[1])


col_list=["openDt","year","month","day","movieNm","movieNmEn","directorpeopleNm"]
movieDOF = movieDOF.loc[:,col_list]
movieDOF

,openDt,year,month,day,movieNm,movieNmEn,directorpeopleNm
movieCd,,,,,,,
20201864,,,,,바디캠,20201864,말릭 비탈
20183385,,,,,카오산 탱고,20183385,김범삼
20209954,,,,,광주비디오: 사라진 4시간,20209954,이조훈
20200330,,,,,수능의 탄생,20200330,
20201865,,,,,기린의 날개,20201865,도이 노부히로
...,...,...,...,...,...,...,...
20209882,20200722,2020,07,22,블루 아워,20209882,하코타 유코
20190735,20200723,2020,07,23,마티아스와 막심,20190735,자비에 돌란
20200749,20200723,2020,07,23,파리의 인어,20200749,마티아스 마르지유
20192522,20200723,2020,07,23,슈퍼 레이스,20192522,
20209741,20200729,2020,07,29,모든 것을 벗어던진 특별한 여행,20209741,

In [53]:
import pandas as pd
import urllib.request
import json

tempURL="http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=105d650c6cc06c74308970b42deeca5a&movieCd=20209948"

# http통신 : urlib사용
tempMoviePage=urllib.request.urlopen(tempURL)

#받은 정보를 파이썬의 json으로 변환: json 패키지 활용(한글정보로 인해서 인코딩 디코딩)
tempMovieData=json.loads(tempMoviePage.read().decode("utf8"),encoding="utf8")
tempMovieData

{'movieInfoResult': {'movieInfo': {'movieCd': '20209948',
   'movieNm': '바람아 안개를 걷어가다오',
   'movieNmEn': "Mom's Song",
   'movieNmOg': '',
   'showTm': '73',
   'prdtYear': '2020',
   'openDt': '',
   'prdtStatNm': '개봉예정',
   'typeNm': '장편',
   'nations': [{'nationNm': '한국'}],
   'genres': [{'genreNm': '기타'}],
   'directors': [{'peopleNm': '신동민', 'peopleNmEn': 'SHIN Dong-min'}],
   'actors': [],
   'showTypes': [{'showTypeGroupNm': '2D', 'showTypeNm': '디지털'}],
   'companys': [],
   'audits': [],
   'staffs': []},
  'source': '영화진흥위원회'}}

In [75]:
# 영화의 이름
tempMovieData["movieInfoResult"]["movieInfo"]["movieNm"]
# 영화의 장르
print(tempMovieData["movieInfoResult"]["movieInfo"]["typeNm"])
# 첫번째 배우이름 배역이름
print(tempMovieData["movieInfoResult"]["movieInfo"]["actors"])
print(tempMovieData["movieInfoResult"]["movieInfo"]["actors"])
# 출연한 배우의 수
len(tempMovieData["movieInfoResult"]["movieInfo"]["actors"])

장편
[{'peopleNm': '피에르 니네이', 'peopleNmEn': 'Pierre Niney', 'cast': '', 'castEn': ''}, {'peopleNm': '아나이스 드무스티에', 'peopleNmEn': 'Anais Demoustier', 'cast': '', 'castEn': ''}]
[{'peopleNm': '피에르 니네이', 'peopleNmEn': 'Pierre Niney', 'cast': '', 'castEn': ''}, {'peopleNm': '아나이스 드무스티에', 'peopleNmEn': 'Anais Demoustier', 'cast': '', 'castEn': ''}]

2

In [ ]:
# 기존 DF에 필요한 컬럼 추가: 장르, 1번배우 이름, 1번 배우 배역이름, 출연 배우 숫자
DF["필요한 컬럼 이름 추가"]=""

# 내가 가지고 있는 DF의 가로줄이 몇개인지 확인(len, shape)
for 반복을 숫자로 하는 경우,

# 
for i in ~~~~~~~~
 1. i번째 영화에 대한 상세정보 요청 주소 만들기
 2. i번째 영화에 대한 상세정보 주소를 http통신으로 요청하고 받아서 json 패키지 이용해 변환
 3. i번째 영화에 대해서 받은 상세저보를 가지고 필요한 정보 추출 
 4. 추출 후 i번째 영화에 기록

In [125]:
import time
t1 = time.time()
movieDOF["typeNm"]=""
movieDOF["peopleNm"]=""
movieDOF["cast"]=""
movieDOF["actors"]=""
T=[]
P=[]
C=[]
A=[]
for i in range(0,len(movieDOF)):
    
    
    tempURL="http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=105d650c6cc06c74308970b42deeca5a&movieCd="+movieDOF.index[i]
    tempMoviePage=urllib.request.urlopen(tempURL)
    tempMovieData=json.loads(tempMoviePage.read().decode("utf8"),encoding="utf8")
    if tempMovieData["movieInfoResult"]["movieInfo"]["typeNm"]:
        T.append(tempMovieData["movieInfoResult"]["movieInfo"]["typeNm"])
    else:
        T.append("")
    
    if tempMovieData["movieInfoResult"]["movieInfo"]["actors"]:
        P.append(tempMovieData["movieInfoResult"]["movieInfo"]["actors"][0]["peopleNm"])
    else:
        P.append("")
    if tempMovieData["movieInfoResult"]["movieInfo"]["actors"]:
        C.append(tempMovieData["movieInfoResult"]["movieInfo"]["actors"][0]["cast"])
    else:
        C.append("")
    
    if tempMovieData["movieInfoResult"]["movieInfo"]["actors"]:
        A.append(len(tempMovieData["movieInfoResult"]["movieInfo"]["actors"]))
    else:
        A.append("")
movieDOF["typeNm"]=T
movieDOF["peopleNm"]=P
movieDOF["cast"]=C
movieDOF["actors"]=A
t2 = time.time()
print ("방법2 : " + str(t2-t1))

방법2 : 35.88493847846985

In [10]:
import time
t1 = time.time()

movieDOF["typeNm"]=""
movieDOF["peopleNm"]=""
movieDOF["cast"]=""
movieDOF["actors"]=""

for i in range(0,len(movieDOF)):
    tempURL="http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json"+\
    "?key=105d650c6cc06c74308970b42deeca5a&movieCd="+movieDOF.index[i]
    tempMoviePage=urllib.request.urlopen(tempURL)
    tempMovieData=json.loads(tempMoviePage.read().decode("utf8"),encoding="utf8")
    
    typeNm=tempMovieData["movieInfoResult"]["movieInfo"]["typeNm"]
    peopleNm=tempMovieData["movieInfoResult"]["movieInfo"]["actors"]
    cast=tempMovieData["movieInfoResult"]["movieInfo"]["actors"]
    actors=tempMovieData["movieInfoResult"]["movieInfo"]["actors"]


    if typeNm:
        movieDOF.at[movieDOF.index[i],"typeNm"]=typeNm
    else:
        pass
    if peopleNm:
        movieDOF.at[movieDOF.index[i],"peopleNm"]=peopleNm[0]["peopleNm"]
    else:
        pass
    if cast:
        movieDOF.at[movieDOF.index[i],"cast"]=cast[0]["cast"]
    else:
        pass
    if actors:
        movieDOF.at[movieDOF.index[i],"actors"]=len(actors)
    else:
        pass   
t2 = time.time()
print ("방법2 : " + str(t2-t1))

movieDOF

방법2 : 47.84144639968872

,openDt,year,month,day,movieNm,movieNmEn,directorpeopleNm,typeNm,peopleNm,cast,actors
movieCd,,,,,,,,,,,
20201901,,,,,나이브스 앤 스킨,20201901,제니퍼 리더,장편,,,
20201874,,,,,저예산 알라딘,20201874,,단편,,,
20200329,,,,,"시대유감, 삼풍",20200329,,장편,,,
20183385,,,,,카오산 탱고,20183385,김범삼,장편,홍완표,지하,3
20209954,,,,,광주비디오: 사라진 4시간,20209954,이조훈,장편,,,
...,...,...,...,...,...,...,...,...,...,...,...
20209882,20200722,2020,07,22,블루 아워,20209882,하코타 유코,장편,카호,스나다,6
20200749,20200723,2020,07,23,파리의 인어,20200749,마티아스 마르지유,장편,,,
20192522,20200723,2020,07,23,슈퍼 레이스,20192522,,장편,,,
20190735,20200723,2020,07,23,마티아스와 막심,20190735,자비에 돌란,장편,자비에 돌란,,2
20209741,20200729,2020,07,29,모든 것을 벗어던진 특별한 여행,20209741,,장편,존 클리즈,,1

In [5]:
import time
t1 = time.time()

movieDOF["typeNm"]=""
movieDOF["peopleNm"]=""
movieDOF["cast"]=""
movieDOF["actors"]=""




for i in range(0,len(movieDOF)):
    tempURL="http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json"+\
    "?key=105d650c6cc06c74308970b42deeca5a&movieCd="+movieDOF.index[i]
    tempMoviePage=urllib.request.urlopen(tempURL)
    tempMovieData=json.loads(tempMoviePage.read().decode("utf8"),encoding="utf8")
    


    if tempMovieData["movieInfoResult"]["movieInfo"]["typeNm"]:
        movieDOF.at[movieDOF.index[i],"typeNm"]=tempMovieData["movieInfoResult"]["movieInfo"]["typeNm"]
    else:
        pass
    if tempMovieData["movieInfoResult"]["movieInfo"]["actors"]:
        movieDOF.at[movieDOF.index[i],"peopleNm"]=tempMovieData["movieInfoResult"]["movieInfo"]["actors"][0]["peopleNm"]
    else:
        pass
    if tempMovieData["movieInfoResult"]["movieInfo"]["actors"]:
        movieDOF.at[movieDOF.index[i],"cast"]=tempMovieData["movieInfoResult"]["movieInfo"]["actors"][0]["cast"]
    else:
        pass
    if tempMovieData["movieInfoResult"]["movieInfo"]["actors"]:
        movieDOF.at[movieDOF.index[i],"actors"]=len(tempMovieData["movieInfoResult"]["movieInfo"]["actors"])
    else:
        pass   
t2 = time.time()
print ("방법2 : " + str(t2-t1))

movieDOF

방법2 : 30.689215183258057

,openDt,year,month,day,movieNm,movieNmEn,directorpeopleNm,typeNm,peopleNm,cast,actors
movieCd,,,,,,,,,,,
20209954,,,,,광주비디오: 사라진 4시간,20209954,이조훈,장편,0,,
20201874,,,,,저예산 알라딘,20201874,,단편,0,,
20200363,,,,,대망,20200363,,장편,0,,
20183385,,,,,카오산 탱고,20183385,김범삼,장편,홍완표,지하,3
20201901,,,,,나이브스 앤 스킨,20201901,제니퍼 리더,장편,0,,
...,...,...,...,...,...,...,...,...,...,...,...
20200749,20200723,2020,07,23,파리의 인어,20200749,마티아스 마르지유,장편,0,,
20192522,20200723,2020,07,23,슈퍼 레이스,20192522,,장편,0,,
20190735,20200723,2020,07,23,마티아스와 막심,20190735,자비에 돌란,장편,자비에 돌란,,2
20209741,20200729,2020,07,29,모든 것을 벗어던진 특별한 여행,20209741,,장편,존 클리즈,,1
20200491,20200729,2020,07,29,빅샤크3: 젤리몬스터 대소동,20200491,신우,장편,정의한,빅샤크,5

In [12]:
import time
t1 = time.time()
movieDOF["typeNm"] = ""
movieDOF["peopleNm"] = ""
movieDOF["cast"] = ""
movieDOF["actors"] = ""

i_type = movieDOF.columns.get_loc("typeNm")
i_acn = movieDOF.columns.get_loc("peopleNm")
i_cast = movieDOF.columns.get_loc("cast")
i_castpeo = movieDOF.columns.get_loc("actors")



dataLen = len(movieDOF)
for i in range(0, dataLen):
    tempURL_Part1 = """http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key="""
    keyNum = """430156241533f1d058c603178cc3ca0e"""
    tempURL_Part2 = """&movieCd="""
    movieId = str(movieDOF.index[i])
    tempURL = tempURL_Part1 + keyNum + tempURL_Part2 + movieId
    
    # For Check URL
    tempDataPage = urllib.request.urlopen(tempURL)
    tempData = json.loads(tempDataPage.read().decode("utf-8"), encoding="utf-8")

    movieDOF.iat[i,i_type] = tempData["movieInfoResult"]["movieInfo"]["typeNm"]
    movieDOF.iat[i,i_acn] = len(tempData["movieInfoResult"]["movieInfo"]["actors"])
    
    if len(tempData["movieInfoResult"]["movieInfo"]["actors"]) <1:
        movieDOF.iat[i,i_cast] = ""
    else:
        movieDOF.iat[i,i_cast] = tempData["movieInfoResult"]["movieInfo"]["actors"][0]["cast"]
        movieDOF.iat[i,i_castpeo] =tempData["movieInfoResult"]["movieInfo"]["actors"][0]["peopleNm"]
        
t2 = time.time()
print ("방법2 : " + str(t2-t1))
movieDOF

방법2 : 34.037904500961304

,openDt,year,month,day,movieNm,movieNmEn,directorpeopleNm,typeNm,peopleNm,cast,actors
movieCd,,,,,,,,,,,
20201864,,,,,바디캠,20201864,말릭 비탈,장편,0,,
20183385,,,,,카오산 탱고,20183385,김범삼,장편,3,지하,홍완표
20209954,,,,,광주비디오: 사라진 4시간,20209954,이조훈,장편,0,,
20200330,,,,,수능의 탄생,20200330,,장편,0,,
20201865,,,,,기린의 날개,20201865,도이 노부히로,장편,7,카가 쿄이치로,아베 히로시
...,...,...,...,...,...,...,...,...,...,...,...
20209882,20200722,2020,07,22,블루 아워,20209882,하코타 유코,장편,6,스나다,카호
20190735,20200723,2020,07,23,마티아스와 막심,20190735,자비에 돌란,장편,2,,자비에 돌란
20200749,20200723,2020,07,23,파리의 인어,20200749,마티아스 마르지유,장편,0,,
20192522,20200723,2020,07,23,슈퍼 레이스,20192522,,장편,0,,
20209741,20200729,2020,07,29,모든 것을 벗어던진 특별한 여행,20209741,,장편,1,,존 클리즈